http://localhost:4000/
###
http://localhost:4000/block
###
http://localhost:4000/status
###
POST http://localhost:4000/block

###
http://localhost:4000/balance/sungmuk
###
http://localhost:4000/balance/sungmuk?total=true

### 
POST http://localhost:4000/transactions

{
    "to":"sujeong",
    "amount":80
}
###
http://localhost:4000/mempool